miprimerproyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'miprimerproyecto.views.homepage', name='homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^preguntas/$', 'preguntasyrespuestas.views.index', name='preguntas'),
    url(r'^preguntas/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_detalle', name='pregunta_detalle'),
    url(r'^preguntas/crear/$', 'preguntasyrespuestas.views.pregunta_crear',
        name="pregunta_crear"),
    url(r'^preguntas/editar/(?P<pregunta_id>\d+)/$', 'preguntasyrespuestas.views.pregunta_editar',
        name='pregunta_editar'),
    url(r'^login/$', 'miprimerproyecto.views.login_page', name='login'),
    url(r'^logout/$', 'miprimerproyecto.views.logout_view', name='logout'),
]

preguntasyrespuestas/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Pregunta(models.Model):
	asunto = models.CharField(max_length=200)
	descripcion = models.TextField()
	fecha_publicacion = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.asunto

	def publicado_hoy(self):
		return self.fecha_publicacion.date() == timezone.now().date()

	publicado_hoy.boolean = True
	publicado_hoy.short_description = '¿Preguntado hoy?'

class Respuesta(models.Model):
	Pregunta = models.ForeignKey(Pregunta)
	contenido = models.TextField()
	mejor_respuesta = models.BooleanField("Respuesta preferida", default=False)

	def __str__(self):
		return self.contenido

miprimerproyecto/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

miprimerproyecto/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from miprimerproyecto.forms import LoginForm
from django.contrib.auth import authenticate, login, logout 

def login_page(request):
	message = None
	if request.method == "POST":
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					message = "Te has identificado de modo correcto"
				else:
					message = "Tu usuario está inactivo"
			else:
				message = "Nombre de usuario y/o password incorrecto"
	else:
		form = LoginForm()
	return render_to_response('login.html', {'message':message, 'form':form},
		context_instance=RequestContext(request))


def homepage(request):
	return render_to_response('homepage.html',
		context_instance=RequestContext(request))

def logout_view(request):
	logout(request)
	return redirect('homepage')

preguntasyrespuestas/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http import HttpResponse, Http404
from preguntasyrespuestas.models import Pregunta
from django.template import RequestContext
from preguntasyrespuestas.form import PreguntaForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone


# Create your views here.

def index(request):
	preguntas = Pregunta.objects.all()
	#respuesta_string = "Preguntas <br />"
	#respuesta_string += '<br/>'.join([ "id: %s, asunto: %s" % (p.id, p.asunto) for p in preguntas ])
	#return HttpResponse(respuesta_string)
	return render_to_response('preguntasyrespuestas/index.html', 
									{'preguntas':preguntas})

"""
def pregunta_detalle(request, pregunta_id):
	try:
		pregunta = Pregunta.objects.get(pk=pregunta_id)
	except Pregunta.DoesNotExist:
		raise Http404
	return HttpResponse("%s?" % pregunta.asunto)
"""
def pregunta_detalle(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	#return HttpResponse("%s?" % pregunta.asunto)
	return render_to_response('preguntasyrespuestas/pregunta_detalle.html', 
									{'pregunta': pregunta})


# def pregunta_crear(request):
# 	form = PreguntaForm()
# 	return render_to_response('preguntasyrespuestas/pregunta_crear.html',
# 			{'form':form},
# 			context_instance=RequestContext(request))

@login_required
def pregunta_crear(request):
	if request.method == 'POST':
		form = PreguntaForm(request.POST)
		if form.is_valid():
			form.save()
			# pregunta = Pregunta(asunto=form.cleaned_data['asunto'],
			# 	descripcion=form.cleaned_data['descripcion'],
			# 	fecha_publicacion=timezone.now())
			# pregunta.save()
			return redirect('preguntas')
	else:
		form = PreguntaForm()
	return render_to_response('preguntasyrespuestas/pregunta_crear.html',
		{'form':form},
		context_instance=RequestContext(request))

@login_required
def pregunta_editar(request, pregunta_id):
	pregunta = get_object_or_404(Pregunta, pk=pregunta_id)
	if request.method == 'POST':
		form = PreguntaForm(request.POST, instance=pregunta)
		if form.is_valid():
			form.save()
			return redirect('preguntas')
	else:
		form = PreguntaForm(instance=pregunta)
	return render_to_response('preguntasyrespuestas/pregunta_editar.html',
		{'form':form},
		context_instance=RequestContext(request))

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Curso de Django | {% block title %} Inicio {% endblock %}</title>
</head>
<body>
	<div id="header">
		{% if user.is_authenticated %}
			<p>
			Bienvenido, <br> {{ user.username }}<br> | 
			<a href="{% url "logout" %}">logout</a><br>
			</p>
		{% else %}
			<p>Bienvenido. Por favor <a href="{% url "login" %}">Login</a></p>
		{% endif %}
		<h1>Curso de Django. Videotutoriales.com</h1>
	</div>
	<div id="content">
		{% block content %}

		{% endblock %}
	</div>
	<div id="navigation">
		<p>
			<a href="{% url "homepage" %}">Inicio</a> |
			<a href="{% url "preguntas" %}">Preguntas</a>
		</p>
	</div>

</body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
	<h1>Bienvenido, Mi primera aplicación web</h1>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}
{% block content %}
	<h1>Login</h1>
	{% if message %}
		<b>{{ message }}</b>
	{% endif %}
	<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" name="" value="Submit">
	</form>
{% endblock %}

templates/preguntasyrespuestas/form_snippets.html
{% for field in form %}
	<div class="field_container">
		{{ field.errors }}
		{{ field.label_tag }} <br>
		{{ field }}
	</div>
{% endfor %}

templates/preguntasyrespuestas/index.html
{% extends "base.html" %}
{% block title %} Questions {% endblock %}
{% block content %}
	<p><a href="{% url "pregunta_crear" %}">Crear Pregunta</a></p>
	{% for pregunta in preguntas %}
		<a href="{% url "pregunta_detalle" pregunta.id %}">{{ pregunta.asunto }} ?</a><br/>
	{% endfor %}
{% endblock %}

templates/preguntasyrespuestas/pregunta_crear.html
{% extends "base.html" %}
{% block title %}Crear un pregunta{% endblock %}
{% block content %}
	<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
		{% include "preguntasyrespuestas/form_snippets.html" %}
		<input type="submit" value="Submit">
	</form>
{% endblock %}

templates/preguntasyrespuestas/pregunta_detalle.html
{% extends "base.html" %}
{% block title %} Respuestas {% endblock %}
{% block content %}
	<h2>{{ pregunta.asunto }}</h2>
	<p><a href="{% url "pregunta_editar" pregunta.id %}">Editar esta pregunta</a></p>
	<p>
		<h4>Publicado: </h4><br>
		{{ pregunta.fecha_publicacion|date:"D, d/m/Y" }}
	</p>
	<p>
		{% if pregunta.descripcion %}
		 	{{ pregunta.descripcion }}
		{% else %}
			No se ha incluido descripcion
		{%endif%}
	</p>
	<h3>Respuesta</h3>
	<ul>
		{% for respuesta in pregunta.respuesta_set.all %}
			<li>{{ respuesta.contenido|safe }}</li>
		{% empty %}
			<li>Aún no hay respùestas...</li>
		{% endfor %}
	</ul>
{% endblock %}

templates/preguntasyrespuestas/pregunta_editar.html
{% extends "base.html" %}
{% block title %}Editar una pregunta{% endblock %}
{% block content %}
	<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
		{% include "preguntasyrespuestas/form_snippets.html" %}
		<input type="submit" value="Submit">
	</form>
{% endblock %}